// keyoku export — bake an approved workflow into a repo as a Claude Code skill.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterAll, describe, expect, it } from "vitest";

import { parse as parseYaml } from "yaml";

import { Store } from "../src/store.js";

const ENTRY = join(__dirname, "..", "dist", "index.js");

const home = mkdtempSync(join(tmpdir(), "keyoku-export-home-"));
const repo = mkdtempSync(join(tmpdir(), "keyoku-export-repo-"));

afterAll(() => {
  rmSync(home, { recursive: true, force: true });
  rmSync(repo, { recursive: true, force: true });
});

describe("keyoku export", () => {
  it("writes a SKILL.md with provenance and run instructions", () => {
    const store = new Store(home);
    store.saveTemplate({
      id: "tmpl_x",
      slug: "deploy-staging",
      name: "Deploy staging",
      description: "Test, build, ship to staging",
      steps: [
        { type: "bash", summary: "run tests", command: "npm test" },
        { type: "agent_prompt", summary: "verify health", prompt: "Check staging health" },
      ],
      trigger: { type: "on_demand" },
      approvedAt: "2026-06-10T00:00:00Z",
      createdAt: "2026-06-10T00:00:00Z",
      updatedAt: "2026-06-10T00:00:00Z",
      timesRun: 4,
    });

    const out = execFileSync(
      process.execPath,
      [ENTRY, "export", "deploy-staging", "--dir", join(repo, ".claude", "skills")],
      { env: { ...process.env, KEYOKU_HOME: home } as NodeJS.ProcessEnv, encoding: "utf8" },
    );
    expect(out).toContain("Baked 'deploy-staging'");

    const skill = readFileSync(join(repo, ".claude", "skills", "deploy-staging", "SKILL.md"), "utf8");
    const fm = parseYaml(skill.split("---")[1]);
    expect(fm.name).toBe("deploy-staging");
    expect(fm.description).toContain("Test, build, ship to staging");
    expect(skill).toContain("Generated by keyoku");
    expect(skill).toContain('workflow_execute { "slug": "deploy-staging" }');
    expect(skill).toContain("run `npm test`");
    expect(skill).toContain("(agent step) Check staging health");
  });

  it("emits VALID YAML frontmatter even when the description contains a colon", () => {
    const store = new Store(home);
    store.saveTemplate({
      id: "tmpl_c",
      slug: "colon-desc",
      name: "Colon desc",
      description: "Deploy: build, then ship — see #ops [urgent]",
      steps: [{ type: "bash", summary: "go", command: "echo go" }],
      trigger: { type: "on_demand" },
      approvedAt: "2026-06-10T00:00:00Z",
      createdAt: "2026-06-10T00:00:00Z",
      updatedAt: "2026-06-10T00:00:00Z",
      timesRun: 1,
    });
    execFileSync(
      process.execPath,
      [ENTRY, "export", "colon-desc", "--dir", join(repo, ".claude", "skills")],
      { env: { ...process.env, KEYOKU_HOME: home } as NodeJS.ProcessEnv, encoding: "utf8" },
    );
    const skill = readFileSync(join(repo, ".claude", "skills", "colon-desc", "SKILL.md"), "utf8");
    // The frontmatter must parse as YAML and preserve the colon-bearing text.
    const fm = parseYaml(skill.split("---")[1]);
    expect(fm.name).toBe("colon-desc");
    expect(fm.description).toContain("Deploy: build, then ship");
  });

  it("fails cleanly for unknown workflows", () => {
    expect(() =>
      execFileSync(process.execPath, [ENTRY, "export", "nope"], {
        env: { ...process.env, KEYOKU_HOME: home } as NodeJS.ProcessEnv,
        encoding: "utf8",
        stdio: "pipe",
      }),
    ).toThrow();
  });
});
